CREATE TABLE IF NOT EXISTS clients (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, profile TEXT NOT NULL, account_id TEXT, primary_region TEXT NOT NULL, dr_region TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX IF NOT EXISTS idx_clients_name ON clients(name);
CREATE UNIQUE INDEX IF NOT EXISTS idx_clients_profile ON clients(profile);
CREATE TABLE IF NOT EXISTS aws_accounts (id INTEGER PRIMARY KEY AUTOINCREMENT, client_id INTEGER NOT NULL, account_id TEXT NOT NULL, alias TEXT, last_sync_at TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX IF NOT EXISTS idx_aws_accounts_account_id ON aws_accounts(account_id);
CREATE INDEX IF NOT EXISTS idx_aws_accounts_client_id ON aws_accounts(client_id);
CREATE TABLE IF NOT EXISTS servers (id INTEGER PRIMARY KEY AUTOINCREMENT, client_id INTEGER NOT NULL, instance_id TEXT, name TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'Unclassified EC2 Instance', environment TEXT, state TEXT, instance_type TEXT, vcpu INTEGER, memory_mib INTEGER, platform TEXT, ami_id TEXT, launch_time TEXT, public_ip TEXT, private_ip TEXT, vpc_id TEXT, subnet_id TEXT, region TEXT NOT NULL, availability_zone TEXT, tags_json TEXT, raw_metadata_json TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX IF NOT EXISTS idx_servers_client_instance ON servers(client_id, instance_id);
CREATE INDEX IF NOT EXISTS idx_servers_client_region ON servers(client_id, region);
CREATE TABLE IF NOT EXISTS billing_months (id INTEGER PRIMARY KEY AUTOINCREMENT, client_id INTEGER NOT NULL, month TEXT NOT NULL, period_start TEXT, period_end TEXT, currency TEXT NOT NULL DEFAULT 'USD', pre_tax_cents INTEGER NOT NULL, tax_cents INTEGER NOT NULL, total_cents INTEGER NOT NULL, provider TEXT NOT NULL, source_sha256 TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX IF NOT EXISTS idx_billing_client_month ON billing_months(client_id, month);
CREATE TABLE IF NOT EXISTS billing_service_costs (id INTEGER PRIMARY KEY AUTOINCREMENT, billing_month_id INTEGER NOT NULL, service TEXT NOT NULL, amount_cents INTEGER NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX IF NOT EXISTS idx_billing_service ON billing_service_costs(billing_month_id, service);
CREATE TABLE IF NOT EXISTS billing_usage_details (id INTEGER PRIMARY KEY AUTOINCREMENT, billing_month_id INTEGER NOT NULL, service TEXT NOT NULL, region TEXT, description TEXT NOT NULL, quantity_microunits INTEGER, unit TEXT, amount_cents INTEGER NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_billing_usage_month_service ON billing_usage_details(billing_month_id, service);
CREATE TABLE IF NOT EXISTS sync_runs (id INTEGER PRIMARY KEY AUTOINCREMENT, client_id INTEGER, scope TEXT NOT NULL, service TEXT NOT NULL, status TEXT NOT NULL, started_at TEXT NOT NULL, finished_at TEXT, error_code TEXT, error_message TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_sync_runs_client_started ON sync_runs(client_id, started_at);
CREATE TABLE IF NOT EXISTS alerts (id INTEGER PRIMARY KEY AUTOINCREMENT, client_id INTEGER NOT NULL, resource_type TEXT, resource_id TEXT, severity TEXT NOT NULL, code TEXT NOT NULL, title TEXT NOT NULL, reason TEXT NOT NULL, observed_at TEXT NOT NULL, resolved_at TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_alerts_client_open ON alerts(client_id, resolved_at);
CREATE TABLE IF NOT EXISTS administrators (id INTEGER PRIMARY KEY AUTOINCREMENT, external_user_id TEXT NOT NULL, email TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, last_seen_at TEXT);
CREATE UNIQUE INDEX IF NOT EXISTS idx_admin_external_user ON administrators(external_user_id);
PRAGMA optimize;
