import { sql } from "drizzle-orm";
import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

const timestamps = {
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
};

export const clients = sqliteTable("clients", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(), profile: text("profile").notNull(), accountId: text("account_id"),
  primaryRegion: text("primary_region").notNull(), drRegion: text("dr_region").notNull(), ...timestamps,
}, (table) => [uniqueIndex("idx_clients_name").on(table.name), uniqueIndex("idx_clients_profile").on(table.profile)]);

export const awsAccounts = sqliteTable("aws_accounts", {
  id: integer("id").primaryKey({ autoIncrement: true }), clientId: integer("client_id").notNull(),
  accountId: text("account_id").notNull(), alias: text("alias"), lastSyncAt: text("last_sync_at"), ...timestamps,
}, (table) => [uniqueIndex("idx_aws_accounts_account_id").on(table.accountId), index("idx_aws_accounts_client_id").on(table.clientId)]);

export const servers = sqliteTable("servers", {
  id: integer("id").primaryKey({ autoIncrement: true }), clientId: integer("client_id").notNull(),
  instanceId: text("instance_id"), name: text("name").notNull(), role: text("role").notNull().default("Unclassified EC2 Instance"),
  environment: text("environment"), state: text("state"), instanceType: text("instance_type"), vcpu: integer("vcpu"),
  memoryMib: integer("memory_mib"), platform: text("platform"), amiId: text("ami_id"), launchTime: text("launch_time"),
  publicIp: text("public_ip"), privateIp: text("private_ip"), vpcId: text("vpc_id"), subnetId: text("subnet_id"),
  region: text("region").notNull(), availabilityZone: text("availability_zone"), tagsJson: text("tags_json"), rawMetadataJson: text("raw_metadata_json"), ...timestamps,
}, (table) => [uniqueIndex("idx_servers_client_instance").on(table.clientId, table.instanceId), index("idx_servers_client_region").on(table.clientId, table.region)]);

export const ebsVolumes = sqliteTable("ebs_volumes", {
  id: integer("id").primaryKey({ autoIncrement: true }), clientId: integer("client_id").notNull(), serverId: integer("server_id"),
  volumeId: text("volume_id").notNull(), sizeGib: integer("size_gib"), type: text("type"), iops: integer("iops"), throughput: integer("throughput"),
  encrypted: integer("encrypted", { mode: "boolean" }), availabilityZone: text("availability_zone"), state: text("state"), createdOn: text("created_on"), ...timestamps,
}, (table) => [uniqueIndex("idx_ebs_volume_id").on(table.volumeId), index("idx_ebs_client_state").on(table.clientId, table.state)]);

export const snapshots = sqliteTable("snapshots", { id: integer("id").primaryKey({ autoIncrement: true }), clientId: integer("client_id").notNull(), volumeId: integer("volume_id"), snapshotId: text("snapshot_id").notNull(), state: text("state"), sizeGib: integer("size_gib"), startedAt: text("started_at"), encrypted: integer("encrypted", { mode: "boolean" }), region: text("region").notNull(), ...timestamps }, (table) => [uniqueIndex("idx_snapshots_id").on(table.snapshotId)]);
export const s3Buckets = sqliteTable("s3_buckets", { id: integer("id").primaryKey({ autoIncrement: true }), clientId: integer("client_id").notNull(), name: text("name").notNull(), region: text("region"), createdOn: text("created_on"), versioning: text("versioning"), encryption: text("encryption"), lifecycleJson: text("lifecycle_json"), replicationJson: text("replication_json"), publicAccessJson: text("public_access_json"), ...timestamps }, (table) => [uniqueIndex("idx_s3_bucket_name").on(table.name)]);
export const backupItems = sqliteTable("backup_items", { id: integer("id").primaryKey({ autoIncrement: true }), clientId: integer("client_id").notNull(), resourceArn: text("resource_arn"), resourceName: text("resource_name").notNull(), backupType: text("backup_type"), status: text("status"), region: text("region").notNull(), startedAt: text("started_at"), completedAt: text("completed_at"), recoveryPointArn: text("recovery_point_arn"), retentionDays: integer("retention_days"), source: text("source").notNull(), ...timestamps }, (table) => [index("idx_backups_client_status").on(table.clientId, table.status), index("idx_backups_resource_time").on(table.resourceName, table.completedAt)]);
export const vpcs = sqliteTable("vpcs", { id: integer("id").primaryKey({ autoIncrement: true }), clientId: integer("client_id").notNull(), vpcId: text("vpc_id").notNull(), name: text("name"), cidr: text("cidr"), region: text("region").notNull(), state: text("state"), isDefault: integer("is_default", { mode: "boolean" }), ...timestamps }, (table) => [uniqueIndex("idx_vpcs_id").on(table.vpcId)]);
export const subnets = sqliteTable("subnets", { id: integer("id").primaryKey({ autoIncrement: true }), clientId: integer("client_id").notNull(), vpcId: text("vpc_id").notNull(), subnetId: text("subnet_id").notNull(), name: text("name"), cidr: text("cidr"), availabilityZone: text("availability_zone"), public: integer("public", { mode: "boolean" }), ...timestamps }, (table) => [uniqueIndex("idx_subnets_id").on(table.subnetId), index("idx_subnets_vpc").on(table.vpcId)]);
export const securityGroups = sqliteTable("security_groups", { id: integer("id").primaryKey({ autoIncrement: true }), clientId: integer("client_id").notNull(), groupId: text("group_id").notNull(), name: text("name"), vpcId: text("vpc_id"), description: text("description"), ingressJson: text("ingress_json"), egressJson: text("egress_json"), ...timestamps }, (table) => [uniqueIndex("idx_security_groups_id").on(table.groupId)]);
export const networkResources = sqliteTable("network_resources", { id: integer("id").primaryKey({ autoIncrement: true }), clientId: integer("client_id").notNull(), resourceId: text("resource_id").notNull(), type: text("type").notNull(), name: text("name"), region: text("region"), state: text("state"), address: text("address"), metadataJson: text("metadata_json"), ...timestamps }, (table) => [uniqueIndex("idx_network_resource").on(table.clientId, table.resourceId), index("idx_network_type").on(table.clientId, table.type)]);
export const vpnConnections = sqliteTable("vpn_connections", { id: integer("id").primaryKey({ autoIncrement: true }), clientId: integer("client_id").notNull(), vpnId: text("vpn_id").notNull(), name: text("name"), region: text("region"), state: text("state"), customerGatewayId: text("customer_gateway_id"), virtualGatewayId: text("virtual_gateway_id"), telemetryJson: text("telemetry_json"), ...timestamps }, (table) => [uniqueIndex("idx_vpn_id").on(table.vpnId)]);
export const iamPrincipals = sqliteTable("iam_principals", { id: integer("id").primaryKey({ autoIncrement: true }), clientId: integer("client_id").notNull(), arn: text("arn").notNull(), type: text("type").notNull(), name: text("name").notNull(), consoleAccess: integer("console_access", { mode: "boolean" }), mfaEnabled: integer("mfa_enabled", { mode: "boolean" }), accessKeyCount: integer("access_key_count"), oldestAccessKeyDays: integer("oldest_access_key_days"), adminAccess: integer("admin_access", { mode: "boolean" }), policySummaryJson: text("policy_summary_json"), ...timestamps }, (table) => [uniqueIndex("idx_iam_arn").on(table.arn), index("idx_iam_client_type").on(table.clientId, table.type)]);
export const serviceInventory = sqliteTable("service_inventory", { id: integer("id").primaryKey({ autoIncrement: true }), clientId: integer("client_id").notNull(), service: text("service").notNull(), region: text("region").notNull().default("global"), resourceCount: integer("resource_count").notNull().default(0), metadataJson: text("metadata_json"), lastObservedAt: text("last_observed_at"), ...timestamps }, (table) => [uniqueIndex("idx_service_inventory").on(table.clientId, table.service, table.region)]);
export const billingMonths = sqliteTable("billing_months", { id: integer("id").primaryKey({ autoIncrement: true }), clientId: integer("client_id").notNull(), month: text("month").notNull(), periodStart: text("period_start"), periodEnd: text("period_end"), currency: text("currency").notNull().default("USD"), preTaxCents: integer("pre_tax_cents").notNull(), taxCents: integer("tax_cents").notNull(), totalCents: integer("total_cents").notNull(), provider: text("provider").notNull(), sourceSha256: text("source_sha256"), ...timestamps }, (table) => [uniqueIndex("idx_billing_client_month").on(table.clientId, table.month)]);
export const billingServiceCosts = sqliteTable("billing_service_costs", { id: integer("id").primaryKey({ autoIncrement: true }), billingMonthId: integer("billing_month_id").notNull(), service: text("service").notNull(), amountCents: integer("amount_cents").notNull(), ...timestamps }, (table) => [uniqueIndex("idx_billing_service").on(table.billingMonthId, table.service)]);
export const billingUsageDetails = sqliteTable("billing_usage_details", { id: integer("id").primaryKey({ autoIncrement: true }), billingMonthId: integer("billing_month_id").notNull(), service: text("service").notNull(), region: text("region"), description: text("description").notNull(), quantityMicrounits: integer("quantity_microunits"), unit: text("unit"), amountCents: integer("amount_cents").notNull(), ...timestamps }, (table) => [index("idx_billing_usage_month_service").on(table.billingMonthId, table.service)]);
export const alerts = sqliteTable("alerts", { id: integer("id").primaryKey({ autoIncrement: true }), clientId: integer("client_id").notNull(), resourceType: text("resource_type"), resourceId: text("resource_id"), severity: text("severity").notNull(), code: text("code").notNull(), title: text("title").notNull(), reason: text("reason").notNull(), observedAt: text("observed_at").notNull(), resolvedAt: text("resolved_at"), ...timestamps }, (table) => [index("idx_alerts_client_open").on(table.clientId, table.resolvedAt), index("idx_alerts_severity").on(table.severity)]);
export const syncRuns = sqliteTable("sync_runs", { id: integer("id").primaryKey({ autoIncrement: true }), clientId: integer("client_id"), scope: text("scope").notNull(), service: text("service").notNull(), status: text("status").notNull(), startedAt: text("started_at").notNull(), finishedAt: text("finished_at"), errorCode: text("error_code"), errorMessage: text("error_message"), ...timestamps }, (table) => [index("idx_sync_runs_client_started").on(table.clientId, table.startedAt)]);
export const administrators = sqliteTable("administrators", { id: integer("id").primaryKey({ autoIncrement: true }), externalUserId: text("external_user_id").notNull(), email: text("email"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`), lastSeenAt: text("last_seen_at") }, (table) => [uniqueIndex("idx_admin_external_user").on(table.externalUserId)]);
